name: CI
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 6 * * 1"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  quality:
    uses: WyattAu/engineering-standards/.github/workflows/rust-kit.yml@6956b54073bedaaf58ade71a6908a892c9addefd
    with:
      tier: c
      all-features: true
